version: '3'
services:
  mt5:
    image: o0nekov0o/metatrader5-custom:latest
    container_name: metatrader5-custom
    volumes:
      - ./config:/config
    ports:
      - "3000:3000"
      - "8001:8001"
    environment:
      - CUSTOM_USER=admin
      - PASSWORD=tonMotDePasse
